### PR TITLE
#3RYihb3M/17 configure-the-app-to-use-postgres-database

### PR DESCRIPTION
**Pull request by TuyizeeAnastase**
**What does this PR do?**
-Postgre Database configuration

**Description of tasks to be completed**
-installing sequelize package
-initialize package
-create postgre database using terminal
-generate sequelize table attribute for Users table
-migrate Table
-create seeding
-check if users has added using terminal

**How should be manually tested?**
-install sequelize package `npm install sequelize sequelize-cli pg pg-hstore`
-create database
-create .env file add databse connection string
-create seeding
-check if user added using terminal
database

**Relavant trello story**
https://trello.com/c/3RYihb3M/17-configure-the-app-to-use-postgres-database

### CODE REVIEW

**Review by Ntwali-Josue — APPROVED** [review]

**Review by Ally4 — APPROVED** [review]

**Review by Mugema123 — APPROVED** [review]

**Review by blaise82 — CHANGES_REQUESTED** [review]
add commands for the database interaction in your package.json

**Review by TuyizeeAnastase — COMMENTED** [review]
yeah, Let add script for migrating and seeding, thank you @blaise82

**Review by TuyizeeAnastase — COMMENTED** [review]
@blaise82  changes from scripts has been added.

**Comment by TuyizeeAnastase** [comment]
> add commands for the database interaction in your package.json

**Comment by ceelogre** [comment]
I'm unable to run `npm install`
Capture d’écran 2020-09-28 à 11 42 15

**Pull request closed without merging**
